app_admin_brand:
    resource: |
        alias: app.brand
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        except: ['show']
        redirect: update
        grid: app_admin_brand
        form:
            type: App\Form\Type\BrandType
    type: sylius.resource
    prefix: /admin

app_shop_product_brand:
    path: /{_locale}/brand/{slug}/{brandSlug}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product::indexAction
        _sylius:
            template: "bundles/SyliusShopBundle/brand/index.html.twig"
            grid: app_shop_brand
    requirements:
        slug: .+(?<!/)
        brandSlug: .+(?<!/)

app_shop_brands_show:
    path: /{_locale}/brands
    methods: [GET]
    defaults:
        _controller: app.controller.brand::indexAction
        _sylius:
            template: "bundles/SyliusShopBundle/brand/show/show.html.twig"
            paginate: false
            sortable: true
            sorting:
                name: asc
     