sylius_admin_brand:
    resource: |
        alias: sylius.brand
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        redirect: update
        grid: sylius_admin_brand
        form:
            type: App\Form\Type\BrandType
        vars:
            all:
                header: Brands
                subheader: Brands
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: /admin