sylius_admin_brand:
    resource: |
        alias: sylius.brand
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        redirect: update
        grid: sylius_admin_brand
        form:
            type: App\Form\Type\BrandType
        vars:
            all:
                subheader: Brands
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: /admin

sylius_shop_product_brand:
    path: /{_locale}/brand/{slug}/{brandSlug}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product::indexAction
        _sylius:
            template: "bundles/SyliusShopBundle/brand/index.html.twig"
            grid: sylius_shop_brand
    requirements:
        slug: .+(?<!/)
        brandSlug: .+(?<!/)

sylius_shop_brands_show:
    path: /{_locale}/brands
    methods: [GET]
    defaults:
        _controller: sylius.controller.product::showAction
        _sylius:
            template: "bundles/SyliusShopBundle/brand/show/show.html.twig"